using System.Text;

namespace ReplayWorkbench.Updater;

/// <summary>
/// Turns the mirrored <c>diffs/*.diff.json</c> into <c>docs/patchdiffs.js</c>, the
/// single data file both the web workbench and the desktop core read.
///
/// <para>Port of tools/build_patchdiffs.py. The rendering is deliberately
/// byte-for-byte identical to the Python: that file is the differential oracle
/// this port is tested against, and a formatting drift would hide a real one.</para>
/// </summary>
public static class PatchDiffsWriter
{
    public const string PackAlphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_";
    private const int PackMax = 64 * 64; // two characters per opcode

    public static string Pack(IEnumerable<int> values)
    {
        var sb = new StringBuilder();
        foreach (var v in values)
        {
            if (v < 0 || v >= PackMax)
                throw new FatalException(
                    $"opcode 0x{v:x} does not fit the 2-character packing (max 0x{PackMax - 1:x})");
            sb.Append(PackAlphabet[v >> 6]);
            sb.Append(PackAlphabet[v & 63]);
        }
        return sb.ToString();
    }

    /// <summary>One rendered hop: the packed lists, in the order they are written.</summary>
    public sealed record Hop(string Version, string O, string N, string? A, string? R);

    public static (List<Hop> Hops, List<string> Warnings) Build(IReadOnlyList<string> chain, string diffsDir)
    {
        var hops = new List<Hop>();
        var warnings = new List<string>();
        HashSet<int>? prevNews = null;

        foreach (var version in chain.Skip(1))
        {
            var hop = DiffHop.Load(diffsDir, version);
            var olds = hop.Map.Keys.OrderBy(x => x).ToList();
            var news = olds.Select(o => hop.Map[o]).ToList();
            var ambiguous = hop.Ambiguous.OrderBy(x => x).ToList();
            var removed = hop.Removed.OrderBy(x => x).ToList();

            foreach (var (target, sources) in hop.Collisions)
                warnings.Add($"  {version}: 0x{target:x} claimed by " +
                             string.Join(", ", sources.Select(s => $"0x{s:x}")) +
                             " -- both demoted to ambiguous");

            // Each hop's old side should be exactly the previous hop's new side. When
            // it isn't, the chain has a gap — worth saying out loud, because opcodes
            // that fall in the gap silently stop being carried forward.
            if (prevNews is not null)
            {
                var accounted = new HashSet<int>(olds);
                accounted.UnionWith(ambiguous);
                accounted.UnionWith(removed);
                var orphaned = prevNews.Count(o => !accounted.Contains(o));
                if (orphaned > 0)
                    warnings.Add($"  {version}: {orphaned} opcode(s) from the previous patch are absent from this diff");
            }

            hops.Add(new Hop(version, Pack(olds), Pack(news),
                ambiguous.Count > 0 ? Pack(ambiguous) : null,
                removed.Count > 0 ? Pack(removed) : null));
            prevNews = new HashSet<int>(news);
        }
        return (hops, warnings);
    }

    /// <summary>
    /// Render the file. Lines are joined with "\n" here and written with CRLF by
    /// the caller, exactly as the Python does, so the two outputs compare equal.
    /// </summary>
    public static string Render(IReadOnlyList<string> chain, IReadOnlyList<Hop> hops)
    {
        var lines = new List<string>
        {
            "\"use strict\";",
            "/* =====================================================================",
            "   Opcode moves per game patch, generated by tools/build_patchdiffs.py",
            "   from https://github.com/xivdev/opcodediff (diffs/*.diff.json).",
            "   DO NOT EDIT BY HAND -- re-run the generator instead.",
            "",
            "   <patch>.diff.json records which opcode number became which when that",
            "   patch shipped, read out of the binary's IPC vtable. Chaining the hops",
            "   moves a recording from any patch below to any patch above it without",
            "   knowing what a single packet is called, which is why transpose uses",
            "   these and not the IPC name lists: names come from a third-party dump",
            "   that lags patches and has been wrong before.",
            "",
            "   PATCH_CHAIN  oldest patch first. The first entry is the base version;",
            "                every later entry has a hop in PATCH_DIFFS landing on it.",
            "   PATCH_DIFFS  <patch> -> {o,n,a,r}, the hop from the previous patch:",
            "                  o/n  parallel old/new opcode lists (a resolved move)",
            "                  a    opcodes the matcher could not tell apart",
            "                  r    opcodes that went away this patch",
            "                Each list is packed two base64 chars per opcode; decode",
            "                with unpackOpcodes() below.",
            "   ===================================================================== */",
            "",
            $"const PATCH_PACK_ALPHABET = \"{PackAlphabet}\";",
            "const PATCH_PACK_INDEX = (()=>{ const m={}; for(let i=0;i<PATCH_PACK_ALPHABET.length;i++) m[PATCH_PACK_ALPHABET[i]]=i; return m; })();",
            "",
            "// Unpack a packed opcode list back into an array of numbers.",
            "function unpackOpcodes(s){",
            "  if(!s) return [];",
            "  const out=new Array(s.length>>1);",
            "  for(let i=0,j=0;i<s.length;i+=2,j++) out[j]=PATCH_PACK_INDEX[s[i]]*64+PATCH_PACK_INDEX[s[i+1]];",
            "  return out;",
            "}",
            "",
            "const PATCH_CHAIN = [",
        };

        var row = "  ";
        foreach (var v in chain)
        {
            var piece = $"\"{v}\",";
            if (row.Length + piece.Length > 96)
            {
                lines.Add(row.TrimEnd());
                row = "  ";
            }
            row += piece + " ";
        }
        lines.Add(row.TrimEnd().TrimEnd(','));
        lines.Add("];");
        lines.Add("");
        lines.Add("const PATCH_DIFFS = {");
        foreach (var hop in hops)
        {
            var parts = new List<string> { $"o:\"{hop.O}\"", $"n:\"{hop.N}\"" };
            if (hop.A is not null) parts.Add($"a:\"{hop.A}\"");
            if (hop.R is not null) parts.Add($"r:\"{hop.R}\"");
            lines.Add($"  \"{hop.Version}\": {{{string.Join(",", parts)}}},");
        }
        lines.Add("};");
        lines.Add("");
        return string.Join("\n", lines) + "\n";
    }
}
