#!/usr/bin/env python3
"""
Generate docs/afgear.js from tools/Job Gear IDs.csv + tools/item_models.json.

The portrait packet wants ITEM ids; the in-arena PlayerSpawn wants MODEL ids
([model, variant]). This bakes both, per job, so the anonymizer can dress both.
Run resolve_models.py first to produce item_models.json.

    python tools/build_afgear.py
"""

import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.join(HERE, "..", "docs")

# row label -> the class/job IDs that share that AF set
ROW_JOBS = {
    "GLA/PLD": [1, 19], "MRD/WAR": [3, 21], "DRK": [32], "GNB": [37],
    "CNJ/WHM": [6, 24], "SCH": [28], "AST": [33], "SGE": [40],
    "PGL/MNK": [2, 20], "LNC/DRG": [4, 22], "ROG/NIN": [29, 30], "SAM": [34],
    "RPR": [39], "VPR": [41], "ARC/BRD": [5, 23], "MCH": [31], "DNC": [38],
    "THM/BLM": [7, 25], "ARC/SMN": [27, 26], "RDM": [35], "PCT": [42],
    "BLU (Limited)": [36],
}
SLOTS = ["Head", "Chest", "Arm", "Legs", "Feet",
         "Earring", "Neck", "Wrist", "Right Ring", "Left Ring"]


def parts(model_str):
    """ '2001-76-2-0' -> [2001, 76, 2] (model, base/variant, variant/stain). """
    p = str(model_str).split("-")
    return [int(p[0]), int(p[1]) if len(p) > 1 else 0, int(p[2]) if len(p) > 2 else 0]


def main():
    models = json.load(open(os.path.join(HERE, "item_models.json")))

    def armor_model(item):  # [model, variant] from models[0]
        ms = models.get(str(item))
        return parts(ms[0])[:2] if ms else [0, 0]

    def weapon_models(item):  # ([model,base,variant] main, [...] off or None)
        ms = models.get(str(item)) or []
        main = parts(ms[0]) if ms else [0, 0, 0]
        off = parts(ms[1]) if len(ms) > 1 else None
        return main, off

    by_job = {}
    for row in csv.DictReader(open(os.path.join(HERE, "Job Gear IDs.csv"))):
        jobs = ROW_JOBS.get(row["Jobs"])
        if not jobs:
            continue
        def itm(col):
            v = (row[col] or "").strip()
            return 0 if v.lower() == "n/a" else int(v)
        gear = [itm(s) for s in SLOTS]
        gear_models = [armor_model(i) for i in gear]
        main = itm("Mainhand")
        wmain, woff = weapon_models(main)
        entry = {
            "weapon": main, "weaponModel": wmain, "weaponSub": woff,
            "gear": gear, "gearModels": gear_models,
        }
        for j in jobs:
            by_job[j] = entry

    lines = ['"use strict";',
             "/* GENERATED by tools/build_afgear.py from tools/Job Gear IDs.csv +",
             "   tools/item_models.json -- do not edit by hand; re-run the generator.",
             "",
             "   Artifact (Lv100) gear per job, keyed by job/class ID. `gear` holds ITEM",
             "   ids (for the portrait/appearance packet); `gearModels` holds [model,",
             "   variant] (for the in-arena PlayerSpawn armor slots). Weapons are the",
             "   PlayerSpawn u64 model: `weaponModel` is the mainhand [model,base,variant]",
             "   and `weaponSub` the offhand/secondary [model,base,variant] or null. Slot",
             "   order: [head, chest, hands, legs, feet, earrings, neck, wrist, ringR, ringL] */",
             "const JOB_AF_GEAR = {"]
    for j in sorted(by_job):
        e = by_job[j]
        gm = ",".join(f"[{m},{v}]" for m, v in e["gearModels"])
        wm = ",".join(map(str, e["weaponModel"]))
        ws = "null" if e["weaponSub"] is None else "[" + ",".join(map(str, e["weaponSub"])) + "]"
        lines.append(
            f'  {j}: {{weapon:{e["weapon"]}, weaponModel:[{wm}], weaponSub:{ws}, '
            f'gear:[{",".join(map(str, e["gear"]))}], gearModels:[{gm}]}},')
    lines.append("};")
    out = os.path.join(DOCS, "afgear.js")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(by_job)} jobs)")


if __name__ == "__main__":
    main()
