#!/usr/bin/env python3
"""Export the browser tool's data files as JSON for the C# core library.

docs/opcodes.js, docs/patchdiffs.js and docs/afgear.js are the single source of
truth -- they are what the web workbench loads and what update_patch.py /
build_patchdiffs.py / build_afgear.py write.  The C# port needs the same data,
but a .NET app should not ship a JavaScript parser, so this script lifts the
object literals out of those files and writes plain JSON into

    programs/Replay.Workbench.Core/Data/

where the library embeds them as resources.  The JSON is generated, checked in,
and regenerated by re-running this script:

    python tools/export_core_data.py

Run it after any tool that rewrites the .js files (update_patch.py in
particular), or the C# build will keep shipping the previous patch's tables.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "programs" / "Replay.Workbench.Core" / "Data"

# Comments, but only outside string literals.  The data files use // banners and
# /* */ blocks between entries; the values themselves are quoted strings made of
# base64-ish characters, so a string-aware scanner is enough.
def strip_comments(src: str) -> str:
    out = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c == '"':
            j = i + 1
            while j < n and src[j] != '"':
                j += 2 if src[j] == "\\" else 1
            out.append(src[i:j + 1])
            i = j + 1
        elif src.startswith("//", i):
            i = src.find("\n", i)
            if i < 0:
                break
        elif src.startswith("/*", i):
            i = src.find("*/", i)
            if i < 0:
                break
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def extract(src: str, name: str) -> str:
    """The balanced {...} or [...] literal assigned to `name`."""
    m = re.search(r"(?:const|let|var)\s+" + re.escape(name) + r"\s*=\s*", src)
    if not m:
        raise SystemExit(f"{name} not found")
    i = m.end()
    if src[i] not in "{[":
        raise SystemExit(f"{name} is not an object or array literal")
    close = {"{": "}", "[": "]"}[src[i]]
    depth, j, in_str = 0, i, False
    while j < len(src):
        c = src[j]
        if in_str:
            if c == "\\":
                j += 1
            elif c == '"':
                in_str = False
        elif c == '"':
            in_str = True
        elif c in "{[":
            depth += 1
        elif c in "}]":
            depth -= 1
            if depth == 0:
                if c != close:
                    raise SystemExit(f"{name}: mismatched brackets")
                return src[i:j + 1]
        j += 1
    raise SystemExit(f"{name}: unterminated literal")


def js_to_json(lit: str):
    """Parse a JS object literal.  These files are generator output, so the only
    things standing between them and JSON are bare keys and trailing commas."""
    # quote bare identifier / numeric keys: {o:"..", 1:{..}  ->  {"o":"..", "1":{..}
    lit = re.sub(r'([{,]\s*)([A-Za-z_$][\w$]*|\d+)\s*:', r'\1"\2":', lit)
    lit = re.sub(r",(\s*[}\]])", r"\1", lit)
    return json.loads(lit)


def scalar(src: str, name: str) -> str:
    m = re.search(r"(?:const|let|var)\s+" + re.escape(name) + r"\s*=\s*([^;]+);", src)
    if not m:
        raise SystemExit(f"{name} not found")
    return m.group(1).strip()


def write(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(payload, indent=1, sort_keys=False) + "\n"
    path.write_text(text, encoding="utf-8", newline="\r\n")
    print(f"  {path.relative_to(ROOT)}  ({len(text):,} bytes)")


def main() -> int:
    opcodes = strip_comments((DOCS / "opcodes.js").read_text(encoding="utf-8"))
    diffs = strip_comments((DOCS / "patchdiffs.js").read_text(encoding="utf-8"))
    afgear = strip_comments((DOCS / "afgear.js").read_text(encoding="utf-8"))

    latest_patch = json.loads(scalar(opcodes, "LATEST_PATCH"))
    latest_build = int(scalar(opcodes, "LATEST_GAME_BUILD"))
    tables = js_to_json(extract(opcodes, "OPCODE_TABLES"))
    build_to_patch = js_to_json(extract(opcodes, "BUILD_TO_PATCH"))
    chain = js_to_json(extract(diffs, "PATCH_CHAIN"))
    patch_diffs = js_to_json(extract(diffs, "PATCH_DIFFS"))
    job_gear = js_to_json(extract(afgear, "JOB_AF_GEAR"))

    if latest_patch not in chain:
        print(f"warning: LATEST_PATCH {latest_patch} is not in PATCH_CHAIN", file=sys.stderr)

    print("exporting core data:")
    write(OUT / "opcodes.json", {
        "latestPatch": latest_patch,
        "latestGameBuild": latest_build,
        "buildToPatch": build_to_patch,
        "opcodeTables": tables,
    })
    write(OUT / "patchdiffs.json", {"patchChain": chain, "patchDiffs": patch_diffs})
    write(OUT / "afgear.json", job_gear)
    print(f"latest patch {latest_patch} (build {latest_build}), "
          f"{len(chain)} patches in chain, {len(tables)} pasted name tables, "
          f"{len(job_gear)} job gear sets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
